language: erlang
before_install:
  - sudo apt-get install -y qemu-user-static
  - wget http://ftp.debian.org/debian/pool/main/d/debootstrap/debootstrap_1.0.87_all.deb
  - sudo dpkg --force-all -i debootstrap_1.0.87_all.deb
script:
  - sudo bash lepidopter-debootstrap-rootfs_build.sh
  - ls -lh images/
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: 1fv5jA0BK/V82Vkdm/v6x8ZsQIjL5cn5FgyydGv3rKJ3qCqEiJrkDi/D8wrXgw0Il6TThh9yLivvKLzHevVH9WfJWxymwP0yJPieFh0FJBEz3r7DNLCdkmzd+mXjAPLS0dsHnHKcxnEK2u7nLu6TGoRsu/akCiZu4Xyz6bMLMuu7hSMhCg08O0ZwOEQ1lbuojxlBU4LiJpUqEzClslbzwTPtgXjR5OfWojzTbGM187SUXmLySCmSxQD3S9ZjesRWUGDcLILPUjoHtTSW7CIzTg86JEhcSg9aROSKBIG625UplMcXJdhElfPnSrJw0Jm0cZcNOFNlG/Gn4yKJZI3YQr4/LbmzBWo40p4K1hEFuJwa/nKDQV6niUorqf6w1+fZI8htrJS6rpl21O4NEtjfYv8R+TOcO60COZLp4C79FvD/SkoFPIftVhZreo3CElxrTGl1REqJMcjiaBRfSWK77+ysU3tBehpxRvMcediHPsHtpc8xYiaolk+ABEvS0r0HId9mEUloI/59FwW5Djqnep8tTFhJxAT+mlRPz8ujsOMCzex1o8kFvz45qXo1jTW8E/UYZoAIfZxKRLE9EeTaxO9TxcW3E7/p9FV03xc/8lvt3XRlpRKAOFnJ77h6FLSILh4nP6rAyrJ5CFHiBEY6gZuhKTWa7a6p3wbCX4T49XU=
  file: images/*.tar.gz
  on:
    repo: ja-pa/lepidopter
